import type { Metadata } from 'next'
import NavbarProduct from '@/components/navbarProduct'
import { cookies } from 'next/headers'
import { CookiesProvider } from 'next-client-cookies/server';

export const metadata: Metadata = {
    title: 'Official Website Naikin-Footwear',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const isLogin = cookies().get('Authorization')?.value
    return (
        <>
            <NavbarProduct isLogin={isLogin} />
            <CookiesProvider>
                {children}
            </CookiesProvider>
        </>
    )
}
