import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarProduct from '@/components/navbarProduct'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'NAIKIN',
    description: 'Generated by create next app',
}

export default function ProtectComponent({
    children,
}: {
    children: React.ReactNode
}) {

    const isLogin = cookies().get('Authorization')?.value
    if (!isLogin || isLogin.length <= 0) {
        redirect('/login')
    }

    return (
        <div>
            {children}
        </div>
    )
}
